// --- START OF FILE config.js (REVISED) ---

/**
 * Reddit to Kindle: Base Configuration
 * 
 * This file contains all the default settings and the structural template for the configuration.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * 
 * Your personal settings are stored in 'user-config.json', which is created by running 'npm run setup'.
 */

export const defaultConfig = {
    // ========================================
    // EMAIL & KINDLE DELIVERY SETTINGS
    // ========================================
    email: {
        // This setting is configured in user-config.json
        provider: 'gmail', // Default provider. Options: 'gmail', 'gmx'

        // Gmail credentials (placeholders)
        gmail: {
            email: 'YOUR_EMAIL@gmail.com',
            appPassword: 'YOUR_GMAIL_APP_PASSWORD',
        },

        // GMX credentials (placeholders)
        gmx: {
            email: 'YOUR_EMAIL@gmx.com',
            password: 'YOUR_GMX_PASSWORD',
        },

        // Kindle email settings (placeholders)
        kindle: {
            email: 'YOUR_KINDLE_EMAIL@kindle.com',
            subject: 'Convert',
            message: 'Attached is the latest Reddit feed in EPUB format.',
        }
    },

    // ========================================
    // REDDIT NEWSLETTER GENERATION SETTINGS
    // ========================================
    reddit: {
        // --- User-configurable settings ---

        // Reddit OAuth2 Authentication (configured in user-config.json)
        enableOAuth2: false,
        oauth2: {
            clientId: 'YOUR_REDDIT_CLIENT_ID',
            clientSecret: 'YOUR_REDDIT_CLIENT_SECRET',
            userAgent: 'RedditToKindle/2.0.0 by YOUR_REDDIT_USERNAME',
            username: 'YOUR_REDDIT_USERNAME',
            password: 'YOUR_REDDIT_PASSWORD',
        },

        // Image handling settings
        downloadImages: true,

        // Randomize the order of subreddits in the final newsletter
        randomizeSubredditOrder: false,

        // List of subreddits to include in your newsletter.
        subreddits: [
            'worldnews',
            'technology',
            'askreddit',
            'chatgpt'
        ],

        // Default settings for each subreddit.
        defaults: {
            postsPerSubreddit: 5,
            commentsPerPost: 5,
            includeInternalLinks: true,
            includeVideoContent: false,
            skipImageAndGalleryPosts: true,
            skipUnfetchableArticles: false,
            skipAutoModerator: true,
            allowImagePostsIfCantFindOtherPosts: true,
            commentStyle: 'threaded',
            maxCommentDepth: 3,
            minCommentLength: 0,
            sort: 'top',
            timeframe: 'week',
        },

        // --- Application-level settings (Advanced) ---

        // Image optimization settings (requires Sharp library)
        enableImageOptimization: true,
        
        // Image optimization preset: 'default', 'aggressive', 'extreme'
        // User can override in user-config.json
        imageOptimizationPreset: 'default',
        
        maxImageWidth: 1200,
        maxImageHeight: 1600,
        minImageWidth: 300,   // Upscale images smaller than this
        minImageHeight: 200,  // Upscale images smaller than this
        jpegQuality: 50,
        optimizationThreshold: 1 * 1024 * 1024, // 1MB

        // Rate limiting, timeouts, and reliability settings
        requestDelays: {
            oauth2: { betweenSubreddits: 1000, betweenComments: 1000, betweenImages: 500, betweenApiCalls: 1000, after429Error: 5000 },
            unauthenticated: { betweenSubreddits: 6000, betweenComments: 6000, betweenImages: 500, betweenApiCalls: 6000, after429Error: 10000 }
        },
        timeouts: { redditApi: 20000, imageDownload: 30000, mercuryParsing: 15000, galleryParsing: 20000 },
        retries: { maxAttempts: 3, baseDelay: 1000, maxDelay: 10000, exponentialBase: 2, jitterPercent: 0.2 },
        concurrency: { maxConcurrentImages: 3, maxConcurrentApiCalls: 2 },
    },

    // ========================================
    // EPUB GENERATION SETTINGS
    // ========================================
    epub: {
        title: 'Reddit Weekly Newsletter',
        creator: 'Reddit Newsletter Generator',
        language: 'en',
        simplifiedTOC: true,
        hierarchicalTOC: false,
        
        // Cover generation settings
        generateDatedCover: true,  // Automatically generate cover with current date
        baseCoverPath: 'reddit_book_cover.jpg',
        outputCoverPath: 'reddit_book_cover_with_date.jpg',

        // Dynamic filename generation - not user-configurable
        generateFilename: () => {
            const now = new Date();
            const year = now.getFullYear();
            const month = String(now.getMonth() + 1).padStart(2, '0');
            const day = String(now.getDate()).padStart(2, '0');
            const hours = String(now.getHours()).padStart(2, '0');
            const minutes = String(now.getMinutes()).padStart(2, '0');
            return `reddit_${year}-${month}-${day}_${hours}-${minutes}.epub`;
        },
    },

    // ========================================
    // SCRIPT VERSION
    // ========================================
    version: "2.0.0"
};